// Phosphor, SSR safe entry points so each icon tree shakes on its own.
export {ArrowRight} from '@phosphor-icons/react/dist/ssr/ArrowRight';
export {CaretDown} from '@phosphor-icons/react/dist/ssr/CaretDown';
export {FileText} from '@phosphor-icons/react/dist/ssr/FileText';
export {CloudArrowUp} from '@phosphor-icons/react/dist/ssr/CloudArrowUp';
export {SealCheck} from '@phosphor-icons/react/dist/ssr/SealCheck';
export {Check} from '@phosphor-icons/react/dist/ssr/Check';
export {Buildings} from '@phosphor-icons/react/dist/ssr/Buildings';
export {Sparkle} from '@phosphor-icons/react/dist/ssr/Sparkle';
export {LockKey} from '@phosphor-icons/react/dist/ssr/LockKey';
export {DeviceMobile} from '@phosphor-icons/react/dist/ssr/DeviceMobile';
export {CalendarCheck} from '@phosphor-icons/react/dist/ssr/CalendarCheck';
export {Files} from '@phosphor-icons/react/dist/ssr/Files';
export {X} from '@phosphor-icons/react/dist/ssr/X';
export {List} from '@phosphor-icons/react/dist/ssr/List';
export {MicrosoftWordLogo} from '@phosphor-icons/react/dist/ssr/MicrosoftWordLogo';
export {Table} from '@phosphor-icons/react/dist/ssr/Table';
export {MagicWand} from '@phosphor-icons/react/dist/ssr/MagicWand';
export {FileArrowDown} from '@phosphor-icons/react/dist/ssr/FileArrowDown';
