import {Alert,AlertDescription} from './components/ui/alert';
import {Input} from './components/ui/input';
import {Label} from './components/ui/label';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from './components/ui/card';
import React,{useState} from 'react';
import {Button} from './components/ui/button';
import {Icon} from './Icon';
import {getFile,putFile} from './storage';
import {backupLimit,fileReferences,validateBackup} from './backup.mjs';
const encode=(file:Blob)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
export function BackupPanel({state,onRestore}:any){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function backup(){setBusy(true);setError('');try{const files:any[]=[];let bytes=0;for(const ref of fileReferences(state)){const f=await getFile(ref.id,ref.name);if(!f)throw Error(`${ref.name}: asl fayl topilmadi. To‘liq zaxira yaratilmadi.`);bytes+=f.size;if(bytes>backupLimit*.7)throw Error('Zaxira hajmi 100 MBdan oshadi. Server zaxiralash tartibidan foydalaning.');files.push({...ref,type:f.type,base64:await encode(f)})}const data=JSON.stringify({format:'hisobkor-backup',version:1,createdAt:new Date().toISOString(),state,files});if(new Blob([data]).size>backupLimit)throw Error('Zaxira hajmi 100 MBdan oshdi.');const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`hisobkor-zaxira-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Zaxira fayli tayyorlandi. Uni xavfsiz joyda saqlang.')}catch(e:any){setError(e.message||'Zaxira yaratilmadi.')}finally{setBusy(false)}}
 async function restore(file?:File){if(!file)return;setBusy(true);setError('');try{if(state.companies.length||state.docs.length)throw Error('Tiklash faqat bo‘sh ish joyida mumkin.');if(file.size>backupLimit)throw Error('100 MBgacha bo‘lgan zaxira faylini tanlang.');const backup=validateBackup(JSON.parse(await file.text()));for(const f of backup.files){const bytes=Uint8Array.from(atob(f.base64),x=>x.charCodeAt(0));await putFile(f.id,new File([bytes],f.name,{type:f.type||''}))}await onRestore({...backup.state,aiAuto:false});setMessage('Zaxira tiklandi. AI avtomatik tekshiruvi o‘chirilgan.')}catch(e:any){setError(e instanceof SyntaxError?'Zaxira faylini o‘qib bo‘lmadi. Hisobkor yaratgan JSON faylini tanlang.':e.message||'Zaxira tiklanmadi.')}finally{setBusy(false)}}
 return <div className="flex flex-col gap-4">
  <Card className="gap-4 py-5"><CardHeader className="px-5"><CardTitle className="flex items-center gap-2 text-base"><Icon name="download" className="text-primary"/>Zaxira nusxasini olish</CardTitle><CardDescription>Kompaniyalar, hujjatlar, qarorlar va tarix bitta faylda. Boshqa ish joyiga ko‘chirish uchun ham ishlatiladi.</CardDescription></CardHeader><CardContent className="px-5"><Button variant="outline" disabled={busy} onClick={backup}>{busy?'Tayyorlanmoqda…':'Zaxirani yuklab olish'}</Button></CardContent></Card>
  <Card className="gap-4 py-5"><CardHeader className="px-5"><CardTitle className="flex items-center gap-2 text-base"><Icon name="upload" className="text-primary"/>Zaxiradan tiklash</CardTitle><CardDescription>Avval olingan Hisobkor zaxirasini bo‘sh ish joyiga yuklang. Faylda moliyaviy ma’lumotlar bo‘lishi mumkin.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2 px-5"><Label htmlFor="backup-file">Zaxira fayli</Label><Input id="backup-file" aria-label="Zaxira faylini tanlash" type="file" accept=".json" disabled={busy||state.companies.length>0||state.docs.length>0} onChange={e=>restore(e.target.files?.[0])}/>{state.companies.length>0&&<p className="text-sm text-muted-foreground">Bu ish joyida ma’lumot bor. Tiklash uchun yangi, bo‘sh ish joyidan foydalaning.</p>}</CardContent></Card>
  {error&&<Alert variant="destructive" role="alert"><Icon name="alert"/><AlertDescription>{error}</AlertDescription></Alert>}
  {message&&<Alert role="status"><Icon name="check"/><AlertDescription>{message}</AlertDescription></Alert>}
 </div>
}
