import {Alert} from './components/ui/alert';
import {Input} from './components/ui/input';
import {Label} from './components/ui/label';
import {Card} from './components/ui/card';
import React,{useState} from 'react';
import {Button} from './components/ui/button';
import {Icon} from './Icon';
import {getFile,putFile} from './storage';
import {backupLimit,fileReferences,validateBackup} from './backup.mjs';
const encode=(file:Blob)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
export function BackupPanel({state,onRestore}:any){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function backup(){setBusy(true);setError('');try{const files:any[]=[];let bytes=0;for(const ref of fileReferences(state)){const f=await getFile(ref.id,ref.name);if(!f)throw Error(`${ref.name}: asl fayl topilmadi. To‘liq zaxira yaratilmadi.`);bytes+=f.size;if(bytes>backupLimit*.7)throw Error('Zaxira hajmi 100 MBdan oshadi. Server zaxiralash tartibidan foydalaning.');files.push({...ref,type:f.type,base64:await encode(f)})}const data=JSON.stringify({format:'hisobkor-backup',version:1,createdAt:new Date().toISOString(),state,files});if(new Blob([data]).size>backupLimit)throw Error('Zaxira hajmi 100 MBdan oshdi.');const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`hisobkor-zaxira-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Zaxira fayli tayyorlandi. Uni xavfsiz joyda saqlang.')}catch(e:any){setError(e.message||'Zaxira yaratilmadi.')}finally{setBusy(false)}}
 async function restore(file?:File){if(!file)return;setBusy(true);setError('');try{if(state.companies.length||state.docs.length)throw Error('Tiklash faqat bo‘sh ish joyida mumkin.');if(file.size>backupLimit)throw Error('100 MBgacha bo‘lgan zaxira faylini tanlang.');const backup=validateBackup(JSON.parse(await file.text()));for(const f of backup.files){const bytes=Uint8Array.from(atob(f.base64),x=>x.charCodeAt(0));await putFile(f.id,new File([bytes],f.name,{type:f.type||''}))}await onRestore({...backup.state,aiAuto:false});setMessage('Zaxira tiklandi. AI avtomatik tekshiruvi o‘chirilgan.')}catch(e:any){setError(e instanceof SyntaxError?'Zaxira faylini o‘qib bo‘lmadi. Hisobkor yaratgan JSON faylini tanlang.':e.message||'Zaxira tiklanmadi.')}finally{setBusy(false)}}
 return <div className="backup-panel"><Card className="settings-card"><Icon name="download" size={22}/><h3>Zaxira nusxasini olish</h3><p>Kompaniyalar, hujjatlar, qarorlar va tarix bitta faylda. Boshqa ish joyiga ko‘chirish uchun ham ishlatiladi.</p><Button variant="outline" disabled={busy} onClick={backup}>{busy?'Tayyorlanmoqda…':'Zaxirani yuklab olish'}</Button></Card><Card className="settings-card"><Icon name="upload" size={22}/><h3>Zaxiradan tiklash</h3><p>Avval olingan Hisobkor zaxirasini bo‘sh ish joyiga yuklang. Faylda moliyaviy ma’lumotlar bo‘lishi mumkin.</p><Label className="backup-picker">Zaxira faylini tanlash<Input aria-label="Zaxira faylini tanlash" type="file" accept=".json" disabled={busy||state.companies.length>0||state.docs.length>0} onChange={e=>restore(e.target.files?.[0])}/></Label>{state.companies.length>0&&<p>Bu ish joyida ma’lumot bor. Tiklash uchun yangi, bo‘sh ish joyidan foydalaning.</p>}</Card>{error&&<Alert className="form-error" role="alert">{error}</Alert>}{message&&<Alert className="neutral-note" role="status">{message}</Alert>}</div>
}
